FROM rastasheep/ubuntu-sshd

ENV DEBIAN_FRONTEND=noninteractive

RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

RUN mkdir /etc/keys
RUN mkdir /opt/iac

RUN apt update
RUN apt-get install curl gnupg2
RUN curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
RUN apt-get install software-properties-common 
RUN apt-add-repository "deb [arch=$(dpkg --print-architecture)] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
RUN apt install python3 python3-pip -y
RUN apt-get update \
&& apt-get install --no-install-recommends \
        ca-certificates \
        curl \
        ansible \
        awscli \
        terraform \
        cpanminus \
        jq \
        git \
        iputils-ping \
        libcurl4 \
        libicu60 \
        libunwind8 \
        netcat \
        vim

WORKDIR iac-box
COPY ./start.sh .
COPY ./set_timezone.sh .

RUN chmod +x start.sh
RUN echo "start ssh daemon"
RUN service ssh restart
RUN perl -pi -e 's/StrictHostKeyChecking ask/StrictHostKeyChecking no/o' /etc/ssh/ssh_config
RUN ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa
RUN cd ~/.ssh && \
    cat id_rsa.pub > authorized_keys && \
    chmod 600 authorized_keys
RUN echo "--- DONE ---"

ENTRYPOINT service ssh restart && ./start.sh


